services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'agentdiscoveries'
      MYSQL_USER: 'agentdiscoveries'
      MYSQL_PASSWORD: 'agentdiscoveries'
      MYSQL_ROOT_PASSWORD: 'agentdiscoveries'
    ports:
      - 3306:3306